[appruntime] 150.0.7863.0~1: Use base::UnguessableToken for browser_context_id
Adapt usage of |browser_context_id| after the upstream CL
http://crrev.com/c/7735657 which replaces return type
of page_node->GetBrowserContextID() to base::UnguessableToken instead of
std::string.

Error message without this commit:
../../neva/app_runtime/browser/performance_manager/policies/page_discarding_helper.cc:381:34: error: no viable conversion from 'const base::UnguessableToken' to 'const std::string' (aka 'const basic_strin
g<char>')
  381 |   if (IsPageOptedOutOfDiscarding(page_node->GetBrowserContextID(),

Issue: NEVA-11248