[neva_extensions] 149.0.7815.0~1: Remove scripting.idl and related feature definitions
In the upstream CL http://crrev.com/c/7784831 moved the Scripting API
and its implementations from //chrome to //extensions.

It caused linker errors like the following:
| build step: solink "libcbe.so"
| siso_rule: clang/solink
| stderr:
| ld.lld: error: duplicate symbol: extensions::api::scripting::ToString(extensions::api::scripting::StyleOrigin)
| >>> defined at scripting.cc
| >>>            generated_api_types/scripting.o:(extensions::api::scripting::ToString(extensions::api::scripting::StyleOrigin)) in archive obj/extensions/common/api/libgenerated_api_types.a
| >>> defined at scripting.cc
| >>>            generated_api_types/scripting.o:(.text+0x0) in archive obj/neva/extensions/common/api/libgenerated_api_types.a

The Scripting API is generated in //extensions/common/api, while
Neva Extensions API still defined and generated the same API.

This resulted in duplicate symbol linker errors due to two copies of
generated_api_types (from //extensions and //neva) defining identical
symbols in extensions::api::scripting.

Removed scripting.idl and related feature definitions from
Neva Extensions API to use upstream implementation.

Issue: NEVA-11212