[appruntime][neva_extensions] 147.0.7720.0~1: Add missing |service_worker_token| usage to AppRuntimeContentRendererClient
In the upstream CL https://crrev.com/c/7567646 |service_worker_token|
has been added into DidStartServiceWorkerContextOnWorkerThread() and
WillDestroyServiceWorkerContextOnWorkerThread() in ContentRendererClient
class which is overriden by AppRuntimeContentRendererClient. So, adapted
AppRuntimeContentRendererClient class accordingly.

Without this patch the build fails with errors like:
../../neva/app_runtime/renderer/app_runtime_content_renderer_client.h:88:31: error: non-virtual member function marked 'override' hides virtual member function
   88 |       const GURL& script_url) override;
      |                               ^
../../content/public/renderer/content_renderer_client.h:393:16: note: hidden overloaded virtual function 'content::ContentRendererClient::DidStartServiceWorkerContextOnWorkerThread' declared here: different number of parameters (4 vs 3)
  393 |   virtual void DidStartServiceWorkerContextOnWorkerThread(
      |                ^

Issue: NEVA-11092