[appruntime][neva_extensions] 149.0.7827.0~1: Adapt usage of Insert() from ProcessMap
In the upstream CL https://crrev.com/c/7793314 migrated ProcessMap
to use ChildProcessId, so this commit adapted it.

Without this change build failed with the error:
../../neva/app_runtime/browser/app_runtime_content_browser_client.cc:653:33: error: no viable conversion from 'int' to 'content::ChildProcessId' (aka 'base::IdType<class ChildProcessIdTag, int, kInvalidChildProcessUniqueId, 1, 0>')
  653 |       ->Insert(extension->id(), site_instance->GetProcess()->GetDeprecatedID());
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Issue: NEVA-11214