[appruntime] 151.0.7880.0~1: Use ByteSize instead of ByteCount in PageDiscardingHelper class
In the upstream CL https://crrev.com/c/7877415 converted deprecated
ByteCount to ByteSize in components/memory_pressure. Neva's
PageDiscardingHelper class is using ByteCount and it is causing build
errors like:
../../neva/app_runtime/browser/performance_manager/policies/page_discarding_helper.cc:206:27:
error: no viable conversion from 'base::ByteSize' to 'const base::ByteCount'
  206 |     const base::ByteCount reclaim_target_value = reclaim_target->target;
      |                           ^                      ~~~~~~~~~~~~~~~~~~~~~~
../../base/byte_count.h:46:3: note: candidate constructor not viable:
no known conversion from 'base::ByteSize' to 'const ByteCount &' for 1st argument
   46 |   ByteCount(const ByteCount&) = default;

So PageDiscardingHelper adapted to use ByteSize instead of ByteCount.

Issue: NEVA-11286