[build] 153.0.7992.0~1: libyuv: Update patch "Disable Neon DotProduct and I8MM instructions in libyuv"
The Neva patch "Disable Neon DotProduct and I8MM instructions in libyuv"
doesn't apply to libyuv successfully due to changes in the upstream
libyuv CLs
- https://chromium-review.googlesource.com/c/libyuv/libyuv/+/8177664
- https://chromium-review.googlesource.com/c/libyuv/libyuv/+/8177647
- https://chromium-review.googlesource.com/c/libyuv/libyuv/+/8175442
which were rolled into Chromium in the upstream CLs
- https://crrev.com/c/8181086
- https://crrev.com/c/8177647
- https://crrev.com/c/8175442
respectively.

The patch is updated to be compatible with the updated libyuv codebase.

Error message without this commit:
Error: Command 'git -C src/third_party/libyuv am ../../neva/patches/0009-build-webos-Disable-Neon-DotProduct-and-I8MM-extensions-in-libyuv.patch' returned non-zero exit status 128 in /mnt/sda/workspace/chromium
error: patch failed: include/libyuv/row.h:554
error: include/libyuv/row.h: patch does not apply
error: patch failed: source/row_neon64.cc:2793
error: source/row_neon64.cc: patch does not apply

Issue: NEVA-11379