[wamdemo] 147.0.7714.0~1: Use OriginatingProcessId instead of OriginatingProcess in emulator_data_source.cc
In the upstream CL https://crrev.com/c/7603876
the network::OriginatingProcess was renamed to
network::OriginatingProcessId. This change was adapted in
emulator_data_source.cc to avoid the following build error:
../../neva/emulator/emulator_data_source.cc:92:16: error: no member
named 'OriginatingProcess' in namespace 'network'; did you mean 'OriginatingProcessId'?
   92 |       network::OriginatingProcess::browser();
      |       ~~~~~~~~~^~~~~~~~~~~~~~~~~~
      |                OriginatingProcessId
../../services/network/public/cpp/originating_process_id.h:18:42:
note: 'OriginatingProcessId' declared here
   18 | class COMPONENT_EXPORT(NETWORK_CPP_BASE) OriginatingProcessId {
      |                                          ^
1 error generated.

Issue: NEVA-11077