[neva_extensions] Adapt TabsCaptureVisibleTabFunction::GetScreenshotAccess()
After the upstream CL http://crrev.com/c/8036583 ScreenshotAccess was
removed and replaced by new extensions::ScreenshotAccessError.
Adapted the return type and body of
TabsCaptureVisibleTabFunction::GetScreenshotAccess() accordingly.

Error message without this commit:
../../neva/extensions/browser/api/tabs/tabs_api.h:146:3: error: unknown type name 'ScreenshotAccess'
  146 |   ScreenshotAccess GetScreenshotAccess(
      |   ^

Issue: NEVA-11355