[neva_extensions] 147.0.7720.0~1: Use std::vector instead of std::ranges::operator| in cookies_api.cc
In the upstream CL https://crrev.com/c/7613978 enabled std::ranges pipe
operator check in Clang plugin. 'clang_use_chrome_plugins' disabled for
ICECC usage and webOS build.
std::ranges::operator|, along with std::views::filter and
std::views::transform, were used in the implementation
of CookiesGetAllFunction::GetAllCookiesCallback().
This CL changed the implementation
of CookiesGetAllFunction::GetAllCookiesCallback() using std::vector.

Without this patch the build fails with errors:
../../neva/extensions/browser/api/cookies/cookies_api.cc:140:16: error: [chromium-style] Use of operator| with range adaptors is banned.
  140 |             }) |
      |                ^
../../neva/extensions/browser/api/cookies/cookies_api.cc:138:25: error: [chromium-style] Use of operator| with range adaptors is banned.
  138 |   auto it = cookie_list | std::views::filter([&domain](const auto& cookie) {
      |                         ^

Issue: NEVA-11092