[appruntime][neva_extensions] 148.0.7733.0~1: Adapt usage of BindForRenderer() from RendererHost and EventRouter
In the upstream CL https://crrev.com/c/7621912 migrated EventRouter and
helpers to ChildProcessId, so this CL adapted it.

Without this change build failed with the errors like:
../../neva/app_runtime/browser/app_runtime_content_browser_client.cc:776:23: error: no matching member function for call to 'AddInterface'
  776 |   associated_registry.AddInterface<extensions::mojom::RendererHost>(
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../neva/app_runtime/browser/app_runtime_content_browser_client.cc:783:23: error: no matching member function for call to 'AddInterface'
  783 |   associated_registry.AddInterface<extensions::mojom::EventRouter>(
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Issue: NEVA-11111