[build] 149.0.7781.0~1: Add missing include of "base/logging.h"
After the unknown upstream CL build fails with errors like:
../../neva/pal_service/system_servicebridge.cc:36:9: error: use of undeclared identifier 'ERROR'
   36 |     LOG(ERROR) << "SystemServiceBridge [ appid = "
      |         ^~~~~

Added missing include of "base/logging.h" in Neva implementations to fix
this issue.

Based on the upstream CL https://crrev.com/c/7732103.

Issue: NEVA-11189