[build] 149.0.7827.0~1: Restore enabling unused-but-set-global check when using ICECC
After the unknown upstream CL build fails with errors like:
../../base/logging.cc:241:6: error: variable 'show_error_dialogs' set but not used [-Werror,-Wunused-but-set-global]
  241 | bool show_error_dialogs = false;

The unused-but-set-global check was mistakenly disabled in the Neva
adaptation https://github.com/nevaoss/chromium/commit/7041549259b8bf636d2ebd23aaa172bf825b41a2,
but to fix this issue, we need to turn it back on.

Issue: NEVA-11191, NEVA-11214