[appruntime] 150.0.7871.0~1 Use HttpRequestHeadersUpdateParams
In the upstream CL http://crrev.com/c/7835814 the signature of the
URLLoader::FollowRedirect() function has been changed.
This patch adapts the overriden
neva_app_runtime::AppRuntimeProxyingURLLoaderFactory::FollowRedirect()
accordingly and fix the following error:
In file included from ../../neva/app_runtime/app/app_runtime_main_delegate.cc:17:
In file included from ../../neva/app_runtime/app/app_runtime_main_delegate.h:25:
In file included from ../../neva/app_runtime/browser/app_runtime_content_browser_client.h:33:
../../neva/app_runtime/browser/net/app_runtime_proxying_url_loader_factory.h:101:45: error: non-virtual member function marked 'override' hides virtual member function
  101 |         const std::optional<GURL>& new_url) override;
      |                                             ^
gen/services/network/public/mojom/url_loader.mojom.h:97:16: note: hidden overloaded virtual function 'network::mojom::URLLoader::FollowRedirect' declared here: different number of parameters (2 vs 4)
   97 |   virtual void FollowRedirect(::network::HttpRequestHeadersUpdateParams headers_update_params, const std::optional<::GURL>& new_url) = 0;

Issue: NEVA-11249