[appruntime][extensions] 146.0.7646.0~1: Adapt to base::Contains() deletion
In the upstream CL https://crrev.com/c/7490440 deleted unused
base::Contains() so this patch adapted it in Neva AppRuntime and
Extensions API.

For memory_saver_mode_policy.cc referred to https://crrev.com/c/7367732
and for extensions referred to https://crrev.com/c/5689773.

Without this change build failed with the build errors:
../../neva/app_runtime/browser/performance_manager/policies/memory_saver_mode_policy.cc:26:10: fatal error: 'base/containers/contains.h' file not found
   26 | #include "base/containers/contains.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../neva/extensions/browser/extension_tab_util.cc:172:10: error: no member named 'Contains' in namespace 'base'; did you mean 'URLPattern::Contains'?
  172 |   return base::Contains(kKillHosts, url.host());
      |          ^~~~~~~~~~~~~~
      |          URLPattern::Contains
../../neva/extensions/browser/extension_tab_util.cc:172:16: error: call to non-static member function without an object argument
  172 |   return base::Contains(kKillHosts, url.host());
      |          ~~~~~~^~~~~~~~

Issue: NEVA-10986