[appruntime] 151.0.7913.0~1: Add missing include <map> to app_runtime_browser_context.h
After unknown upstream CL build fails with error:
In file included from ../../neva/app_runtime/browser/app_runtime_browser_context.cc:17:
../../neva/app_runtime/browser/app_runtime_browser_context.h:77:34:
error: no template named 'map' in namespace 'std'; did you mean 'max'?
   77 |   using BrowserContextMap = std::map<std::string,

So missing include <map> is added to app_runtime_browser_context.h.

Issue: NEVA-11318