[appruntime][neva_extensions] 148.0.7740.0~1: Adapt usage of |process_id| param from ServiceWorkerVersionBaseInfo
In the upstream CL https://crrev.com/c/7664509 migrated
ServiceWorkerInfo to ChildProcessId, so this CL adapted it.

Without this change build failed with the errors:
../../neva/app_runtime/browser/app_runtime_content_browser_client.cc:779:31: error: no viable conversion from 'const ChildProcessId' (aka 'const base::IdType<class ChildProcessIdTag, int, kInvalidChildProcessUniqueId, 1, 0>') to 'int'
  779 |                               service_worker_version_info.process_id)));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../neva/app_runtime/browser/app_runtime_content_browser_client.cc:781:23: error: no matching member function for call to 'AddInterface'
  781 |   associated_registry.AddInterface<extensions::mojom::ServiceWorkerHost>(
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../neva/app_runtime/browser/app_runtime_content_browser_client.cc:787:31: error: no viable conversion from 'const ChildProcessId' (aka 'const base::IdType<class ChildProcessIdTag, int, kInvalidChildProcessUniqueId, 1, 0>') to 'int'
  787 |                               (service_worker_version_info.process_id))));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Issue: NEVA-11125