[neva_extensions] 152.0.7950.0~1: Add missing |browser_context| to NevaExtensionsBrowserClient::LoadResourceFromResourceBundle()
In the upstream CL https://crrev.com/c/8067138 added |browser_context|
param to ExtensionsBrowserClient::LoadResourceFromResourceBundle().

The override of this func in the NevaExtensionsBrowserClient class is
adapted accordingly.

Without this change, the build fails with the following error:
../../third_party/libc++/src/include/__memory/unique_ptr.h:763:30: error: allocating an object of abstract class type 'neva::NevaExtensionsBrowserClient'
  763 |   return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...));
      |                              ^
../../neva/app_runtime/browser/app_runtime_browser_main_parts.cc:169:12: note: in instantiation of function template specialization 'std::make_unique<neva::NevaExtensionsBrowserClient, 0>' requested here
  169 |       std::make_unique<neva::NevaExtensionsBrowserClient>();
      |            ^
../../extensions/browser/extensions_browser_client.h:280:16: note: unimplemented pure virtual method 'LoadResourceFromResourceBundle' in 'NevaExtensionsBrowserClient'
  280 |   virtual void LoadResourceFromResourceBundle(
      |                ^

Issue: NEVA-11357