[build] 147.0.7714.0~1: Adapt call of UpdateForSameDocumentNavigation() in web_local_frame_impl.cc
In the upstream CL https://crrev.com/c/7601536 changed the signature of
DocumentLoader::UpdateForSameDocumentNavigation(). The function now
expects 12 arguments instead of 13. Adjusted the call of
UpdateForSameDocumentNavigation() in WebLocalFrameImpl to match the new
signature to avoid the build error:
../../third_party/blink/renderer/core/frame/web_local_frame_impl.cc:2848:34:
error: too many arguments to function call, expected 12, have 13
 2837 |   GetFrame()->GetDocument()->Loader()->UpdateForSameDocumentNavigation(
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2838 |       blink::KURL(blink::KURL(),
 2839 |                   blink::String::FromUTF8(base::as_byte_span(new_url))),
 2840 |       nullptr, mojom::blink::SameDocumentNavigationType::kHistoryApi, nullptr,
 2841 |       blink::WebFrameLoadType::kReplaceCurrentItem, blink::FirePopstate::kNo,
 2842 |       frame_->DomWindow()->GetSecurityOrigin(),
 2843 |       /*is_browser_initiated=*/true,
 2844 |       /*is_synchronously_committed=*/true,
 2845 |       /*soft_navigation_heuristics_task_id=*/std::nullopt,
 2846 |       HasTransientUserActivation(),
 2847 |       /*has_ua_visual_transition=*/false,
 2848 |       /*should_skip_screenshot=*/false);
      |                                  ^~~~~

Issue: NEVA-11077