[appruntime][neva_extensions] 149.0.7815.0~1: Adapt AppRuntimeContentBrowserClient::RegisterNonNetworkWorkerMainResourceURLLoaderFactories()
In the upstream CL http://crrev.com/c/7784632 added
|request_destination| parameter into
ContentBrowserClient::RegisterNonNetworkWorkerMainResourceURLLoaderFactories()
method, which is overridden in AppRuntimeContentBrowserClient class.
So, adapted RegisterNonNetworkWorkerMainResourceURLLoaderFactories()
method of AppRuntimeContentBrowserClient class accordingly.

Without this patch the following error occurs:
../../neva/app_runtime/browser/app_runtime_content_browser_client.h:138:49: error: non-virtual member function marked 'override' hides virtual member function
  138 |       NonNetworkURLLoaderFactoryMap* factories) override;

Issue: NEVA-11212