[appruntime] 152.0.7950.0~1: Replace ByteCount with ByteSize in user_level_memory_pressure_signal_generator.cc‎
In the upstream CL https://crrev.com/c/8065300 migrated from
deprecated ByteCount to ByteSize in //content.

Adapted the Neva code in user_level_memory_pressure_signal_generator.cc
to use ByteSize instead of ByteCount accordingly.

Without this change, the build fails with the following error:
../../content/browser/memory_pressure/user_level_memory_pressure_signal_generator.cc:118:7: error: no matching constructor for initialization of 'base::ByteSize'
  118 |       memory_threshold_(MemoryThresholdParam()),
      |       ^                 ~~~~~~~~~~~~~~~~~~~~~~
../../base/byte_size.h:156:19: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'base::ByteCount' to 'const ByteSize' for 1st argument
  156 | class BASE_EXPORT ByteSize : public internal::ByteSizeBase {
      |                   ^~~~~~~~

Issue: NEVA-11357