[appruntime] 151.0.7922.0~1: Add missing |extended_net_log_events| to OnBeforeSendHeadersCallback::Run()
In the upstream CL https://crrev.com/c/7976020 added
extended_net_log_events to TrustedHeaderClient::OnBeforeSendHeaders
with adding the extended_net_log_events parameter to the response
callback of OnBeforeSendHeaders. Neva's code is adapted accordingly.
Otherwise build fails with errors like:
../../neva/app_runtime/browser/net/app_runtime_proxying_url_loader_factory.cc:351:25:
error: no matching member function for call to 'Run'
  351 |     std::move(callback).Run(net::OK, std::nullopt);

Isuue: NEVA-11319