[appruntime] 146.0.7649.0~1: Remove include of deleted BFCachePolicy
In the upstream CL https://crrev.com/c/7424585 removed BFCachePolicy
so this CL adapted it in Neva AppRuntime API.

Without this change build failed with the error:
../../neva/app_runtime/browser/performance_manager/app_runtime_browser_main_extra_parts_performance_manager.cc:31:10: fatal error: 'components/performance_manager/graph/policies/bfcache_policy.h' file not found
   31 | #include "components/performance_manager/graph/policies/bfcache_policy.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Issue: NEVA-10991