[build] 150.0.7871.0~1 Replace base::ByteCount with base::ByteSize
In the upstream CL https://crrev.com/c/7878968 base::ByteCount was
replaced with base::ByteSize as part of the initiative
http://issues.chromium.org/issues/448661443.
This patch applies appropriate changes to the Neva code and fixes the
following build errors:
build step: cxx "./obj/cc/cc/image_decode_cache_utils.o"
stderr:
../../cc/tiles/image_decode_cache_utils.cc:50:26: error: invalid operands to binary expression ('base::ByteCount' and 'base::ByteSize')
   50 |             budget_bytes < decoded_image_working_set_budget) {
../../cc/tiles/image_decode_cache_utils.cc:51:44: error: no viable overloaded '='
   51 |           decoded_image_working_set_budget = budget_bytes;

Issue: NEVA-11249