[appruntime] 146.0.7636.0~1: Adapt call of RenderWidgetHostView::CopyFromSurface() in app_runtime_visible_region_capture.cc
In the upstream CL https://crrev.com/c/7454865 added timeouts parameter
to content API for CopyFromSurface so this patch adapted it as
base::TimeDelta() argument.

Without this change build failed with the build error:
../../neva/app_runtime/app/app_runtime_visible_region_capture.cc:63:47: error: too few arguments to function call, expected 4, have 3
   60 |     view->CopyFromSurface(
      |     ~~~~~~~~~~~~~~~~~~~~~
   61 |         gfx::Rect(), gfx::Size(output_width, output_height),
   62 |         base::BindOnce(&VisibleRegionCapture::OnBitmapCaptured,
   63 |                        base::Unretained(this)));
      |                                               ^

Issue: NEVA-10985