[appruntime] 146.0.7649.0~1: Remove unnecessary headers in app_runtime_render_frame_observer.cc
In the upstream CL https://crrev.com/c/7456200 vectorized
StringImpl::CopyChars and EqualIgnoringASCIICase using Highway, which
added the following dependency for blink_platform_wtf component:
"//third_party/highway:libhwy".

Previously Neva added some includes to
//neva/app_runtime/renderer/app_runtime_render_frame_observer.cc,
which now in turn include <hwy/highway.h> which is not supported.
In order to fix the build error the unnecessary includes have been
removed.

Without this change build failed with the build error:
../../third_party/blink/renderer/platform/wtf/text/string_impl.h:27:10: fatal error: 'hwy/highway.h' file not found
   27 | #include <hwy/highway.h>
      |          ^~~~~~~~~~~~~~~

Issue: NEVA-10991