[neva_extensions] 151.0.7880.0~1: Remove unneeded MV2 deprecation dialogs
In the upstream CL https://crrev.com/c/7884079 removed unneeded MV2
deprecation dialogs. Neva implementation had the overriden method, so it
was removed accordingly.
Without this change, the build fails with the following error:
In file included from ../../neva/extensions/browser/neva_extension_api_client.cc:20:
../../neva/extensions/browser/api/management/neva_management_api_delegate.h:92:59:
error: only virtual member functions can be marked 'override'
   92 |       base::OnceCallback<void(bool)> done_callback) const override;

Issue: NEVA-11286