[build] 147.0.7714.0~1: Rust: Adjust usage of ReadUnicodeCharacter() in json_parser.cc
In the upstream CL https://crrev.com/c/7600473 changed signature of
ReadUnicodeCharacter(). So it was adapted in C++ JSON parser to avoid
build error:
../../base/json/json_parser.cc:628:12: error: no matching function for
call to 'ReadUnicodeCharacter'
  628 |       if (!ReadUnicodeCharacter(input_.data(), input_.length(), &index_,
      |            ^~~~~~~~~~~~~~~~~~~~
../../base/strings/utf_string_conversion_utils.h:63:18: note: candidate
function not viable: requires 3 arguments, but 4 were provided

Issue: NEVA-11077