[build][webos] 148.0.7750.0~1: V8: Do not exit function on ICU initialization fail in mksnapshot.cc
In the upstream V8 CL
https://chromium-review.googlesource.com/c/v8/v8/+/7679153, which
is rolled into Chromium in https://crrev.com/c/7684531, added better
error messages for invalid ICU data files.

It caused error on building com.webos.app.test.v8snapshot on webOS/OSE:
ERROR: com.webos.app.test.v8snapshot-1.0.0-25-r6.1 do_compile:
...
| mksnapshot-cross-aarch64: Failed to initialize ICU
| ninja: build stopped: subcommand failed.
|
| WARNING: exit code 1 from a shell command.
ERROR: Task (/ssd/neva-main-rolling/build-webos/meta-lg-webos/meta-webos/recipes-webos/test-apps/com.webos.app.test.v8snapshot.bb:do_compile) failed with exit code '1'

Do not exit function on ICU initialization fail in
v8/src/snapshot/mksnapshot.cc for webOS to fix this issue.

Issue: NEVA-11130