[neva_extensions] 149.0.7794.0~1: Remove GetPrefServiceForContext() from Neva implementation
In the upstream CL https://crrev.com/c/7720140, the
GetPrefServiceForContext() method was removed from the
ExtensionsBrowserClient interface. This commit removes the
implementation of this method from the NevaExtensionsBrowserClient class
to aviod build error:
In file included from
../../neva/app_runtime/browser/app_runtime_browser_context.cc:56:
../../neva/extensions/browser/neva_extensions_browser_client.h:97:41
error: only virtual member functions can be marked 'override'
97 |       content::BrowserContext* context) override;

Issue: NEVA-11191