[build] 147.0.7714.0~1: Add missing headers in local_storage_impl.cc
In the upstream CL https://crrev.com/c/7603214 removed some headers that
are needed for Neva. The following headers were added back to resolve
the build errors:
This change addresses the following errors:
../../components/services/storage/dom_storage/local_storage_impl.cc:235:37:
error: no member named 'DoNothing' in namespace 'base'
  235 |                               base::DoNothing());
      |                                     ^~~~~~~~~
../../components/services/storage/dom_storage/local_storage_impl.cc:272:15:
error: no member named 'StringToSizeT' in namespace 'base'
  272 |     if (base::StringToSizeT(
      |               ^~~~~~~~~~~~~
2 errors generated.

Issue: NEVA-11077