[build] 148.0.7756.0~1: Add global namespace for calling kInitialWebUI and kInitialWebUIHighStreamPriority from feature:: namespace
In the upstream CL http://crrev.com/c/7698514 added call
of kInitialWebUI and kInitialWebUIHighStreamPriority from feature::
namespace, which not visible from content:: namespace because of Neva
content::feature namespace which is included by
//content/common/user_level_memory_pressure_signal_features.h.

It caused build errors:
../../content/renderer/renderer_blink_platform_impl.cc:821:37: error: no member named 'kInitialWebUI' in namespace 'content::features'; did you mean '::features::kInitialWebUI'?
  821 |       (base::FeatureList::IsEnabled(features::kInitialWebUI) &&
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                                     ::features::kInitialWebUI
../../content/public/common/content_features.h:151:37: note: '::features::kInitialWebUI' declared here
  151 | CONTENT_EXPORT BASE_DECLARE_FEATURE(kInitialWebUI);
      |                                     ^
../../content/renderer/renderer_blink_platform_impl.cc:822:8: error: no member named 'kInitialWebUIHighStreamPriority' in namespace 'content::features'; did you mean '::features::kInitialWebUIHighStreamPriority'?
  822 |        features::kInitialWebUIHighStreamPriority.Get() &&
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |        ::features::kInitialWebUIHighStreamPriority                                                                                                            120 | bool IsFontDataServiceEnabled();

Global namespace qualifier was added to the call to kInitialWebUI and
kInitialWebUIHighStreamPriority from feature:: namespace to fix this
issue.

Issue: NEVA-11142