[appruntime][neva_extensions] 149.0.7794.0~1: Adapt AppRuntimeContentBrowserClient::RegisterNonNetworkWorkerMainResourceURLLoaderFactories()
In the upstream CL https://crrev.com/c/7703728 |request_initiator| param
has been added into
RegisterNonNetworkWorkerMainResourceURLLoaderFactories()
in content::ContentBrowserClient class which is overriden by
AppRuntimeContentBrowserClient. So, adapted
AppRuntimeContentBrowserClient::RegisterNonNetworkWorkerMainResourceURLLoaderFactories()
accordingly.

Without this adaptation build fails with error:
../../neva/app_runtime/browser/app_runtime_content_browser_client.h:137:49:
error: non-virtual member function marked 'override' hides virtual member function
   137 |       NonNetworkURLLoaderFactoryMap* factories) override;

Issue: NEVA-11191