[appruntime] 150.0.7871.0~1 Use ShowWithVisibility() instead of deleted Show() for WebView
In the upstream CL http://crrev.com/c/7872137 Show/Hide has been
removed from public RenderWidgetHostView API.
This patch changes the corresponding call for WebView in Neva
AppRuntime API and fix the following error:
../../neva/app_runtime/webview.cc:317:16: error: no member named 'Show' in 'content::RenderWidgetHostViewAura'
  317 |     host_view->Show();

Issue: NEVA-11249