[neva_extensions] 148.0.7733.0~1: Adapt NevaExtensionHostDelegate::CreateTab()
In the upstream CL https://crrev.com/c/7644389 |target_url| param
has been added into CreateTab() in extensions::ExtensionHostDelegate
class which is overriden by NevaExtensionHostDelegate. So, adapted
NevaExtensionHostDelegate::CreateTab() accordingly.

Without this adaptation build fails with error:
../../neva/extensions/browser/neva_extension_host_delegate.h:35:37: error: non-virtual member function marked 'override' hides virtual member function
   35 |                  bool user_gesture) override;

Issue: NEVA-11111