[webos] 153.0.7992.0~1: Adapt LoadDataResourceBytes()
Adaptation of WebosResourceDelegate::LoadDataResourceBytes() after
the upstream CL http://crrev.com/c/8175224 which replaces return type
base::RefCountedMemory* with scoped_refptrbase::RefCountedMemory.

Error message without this commit:
webos/common/webos_resource_delegate.h:39:33: error: virtual function 'LoadDataResourceBytes' has a different return type ('base::RefCountedStaticMemory *') than the
 function it overrides (which has return type 'scoped_refptr<base::RefCountedMemory>')
|    39 |   base::RefCountedStaticMemory* LoadDataResourceBytes(
|       |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

Issue: NEVA-11379