[appruntime] 148.0.7733.0~1: Adapt AppRuntimeTouchSelectionMenuRunner class
In the upstream CL https://crrev.com/c/7631097 |can_paste| param
has been added into IsMenuAvailable() and OpenMenu() in
ui::TouchSelectionMenuRunner class which is overriden
by AppRuntimeTouchSelectionMenuRunner. So, adapted IsMenuAvailable() and
OpenMenu() in AppRuntimeTouchSelectionMenuRunner class accordingly.

Without this adaptation build fails with errors:
../../neva/app_runtime/ui/app_runtime_touch_menu_runner.h:35:57: error: non-virtual member function marked 'override' hides virtual member function
   35 |       const ui::TouchSelectionMenuClient* client) const override;
      |                                                         ^
In file included from ../../neva/app_runtime/ui/app_runtime_touch_menu_runner.cc:17:
../../neva/app_runtime/ui/app_runtime_touch_menu_runner.h:40:40: error: non-virtual member function marked 'override' hides virtual member function
   40 |                 aura::Window* context) override;

Issue: NEVA-11111