[build][webos] 155.0.8041.0~1: V8: Temporary set newer revision in DEPS
In the upstream CL https://crrev.com/c/7864481 was introduced the
"metagen" tool which cheks gn markers. webOS output directory is
placed outside of Chromium source dir.

This led to a build error:
RuntimeError: [metagen] no .gn source-root marker found above

To avoid this error, V8 revision is temporary set to
https://chromium-review.googlesource.com/c/v8/v8/+/8377827 -
V8 version which includes the error fixing CL
https://chromium-review.googlesource.com/c/v8/v8/+/8372543

Issue: NEVA-11447