[appruntime] 146.0.7664.0~1: Replace usage of PermissionsClient::DoURLsMatchNewTabPage() with PermissionsClient::GetEmbeddingOriginOverride()
In the upstream CL http://crrev.com/c/7515301 the implementation of
the origin permission check has been refactored from
DoURLsMatchNewTabPage() to GetEmbeddingOriginOverride().
It caused the following compile error:
../../neva/app_runtime/browser/media/webrtc/device_media_stream_access_handler.cc:96:46: error: no member named 'DoURLsMatchNewTabPage' in 'permissions::PermissionsClient'
   96 |   if (permissions::PermissionsClient::Get()->DoURLsMatchNewTabPage(
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.

Current patch fix this issue.

Issue: NEVA-11014