[build][webos] 155.0.8041.0~1: V8: Change gn desc call for metagen tool
In the upstream CL https://crrev.com/c/7864481 was introduced the
"metagen" tool which cheks gn markers. In Neva build configuration
"gn gen" cmd for mksnapshot is called with additional flags:
--root="..." and --dotfile="...". So these arguments are passed to
"gn desc" call to avoid V8 configuration error:

RuntimeError: [metagen] gn desc failed. Has `gn gen` run there?

Issue: NEVA-11447