[injection] 154.0.8024.0~1: Adapt jin::CreateConstructorTemplate()
In the upstream CL http://crrev.com/c/8279909 migrated
CallbackHolderBase class to gin::Wrappable.

The Neva's jin::CreateConstructorTemplate(), which uses this class, is
adapted according to gin::CreateFunctionTemplate() change in
https://chromium-review.googlesource.com/c/chromium/src/+/8279909/4/gin/function_template.h.

Without this change the build fails with the following errors:
In file included from ../../neva/injection/renderer/browser_shell/browser_shell_injection.cc:35:
../../neva/injection/renderer/gin/function_template_neva.h:31:7: error: call to deleted function 'operator new'
   31 |       new HolderT(isolate, std::move(callback), std::move(invoker_options));
      |       ^~~
../../neva/injection/renderer/browser_shell/browser_shell_injection.cc:105:12: note: in instantiation of function template specialization 'gin::CreateConstructorTemplate<void (gin::Arguments *)>' requested here
  105 |       gin::CreateConstructorTemplate(
      |            ^
../../v8/include/cppgc/garbage-collected.h:59:9: note: candidate function has been explicitly deleted
   59 |   void* operator new(size_t) = delete;
      |         ^

Issue: NEVA-11416