[appruntime][neva_extensions] 148.0.7750.0~1: Adapt usage of BindReceiver() from ServiceWorkerHost
In the upstream CL https://crrev.com/c/7680500 migrated
ServiceWorkerHost to ChildProcessId, so this CL adapted it.

Without this change build failed with the error:
../../neva/app_runtime/browser/app_runtime_content_browser_client.cc:780:23: error: no matching member function for call to 'AddInterface'
  780 |   associated_registry.AddInterface<extensions::mojom::ServiceWorkerHost>(
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Issue: NEVA-11130