[appruntime] 147.0.7714.0~1: Adapt usage of ClearData() in browsing_data_remover.cc
In the upstream CL https://crrev.com/c/7596126, in the StoragePartition
class the QUOTA_MANAGED_STORAGE_MASK_* was removed and the ClearData
function signature was changed. The corresponding adjustments were made
in this CL to match the new signature and avoid the build error:
../../neva/app_runtime/browser/browsing_data/browsing_data_remover.cc:154:25:
error: no matching member function for call to 'ClearData'
  154 |     storage_partition_->ClearData(
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../content/public/browser/storage_partition.h:293:16: note: candidate
 function not viable: requires 5 arguments, but 6 were provided
  293 |   virtual void ClearData(uint32_t remove_mask,
      |                ^         ~~~~~~~~~~~~~~~~~~~~~
  294 |                          const blink::StorageKey& storage_key,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  295 |                          const base::Time begin,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~
  296 |                          const base::Time end,
      |                          ~~~~~~~~~~~~~~~~~~~~~
  297 |                          base::OnceClosure callback) = 0;
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

Issue: NEVA-11077