[build][webos] 155.0.8041.0~1: V8: Explicitly set the source root for V8 metagen tool
In the upstream CL https://crrev.com/c/7864481 was introduced the
"metagen" tool which cheks gn markers. webOS output directory is
placed outside of Chromium source dir.

This led to an error:
RuntimeError: [metagen] no .gn source-root marker found above

So source_root var set explicitly to avoid this error.

Issue: NEVA-11447