[build] 148.0.7764.0~1: Disable is_wexit_time_destructors_default
In the upstream CL https://crrev.com/c/7682084 enabled
exit-time-destructors by default based on build_with_chromium.

It caused build error:
../../third_party/dawn/src/dawn/common/ThreadLocal.cpp:67:35: error: declaration requires an exit-time destructor [-Werror,-Wexit-time-destructors]
   67 |     static thread_local ThreadRef sThreadRef(sNextThreadUniqueId++);

This error occurs because the "-Werror" flag is added to the compiler
for Neva.

Disabled is_wexit_time_destructors_default to fix this issue.

Issue: NEVA-11146