[build] 147.0.7727.0~1: Rust: Disable Rust-based ChildProcessSecurityPolicy
In the upstream CL https://crrev.com/c/7549430 introduced Rust-based
ChildProcessSecurityPolicy. Neva doesn't support Rust, therefore,
Rust-based ChildProcessSecurityPolicy is disabled to avoid configuration
and compile errors:
ERROR at //build/rust/gni_impl/rust_target.gni:43:3: Assertion failed.
  assert(enable_rust)
  ^-----
See //build/rust/rust_static_library.gni:221:3: whence it was called.
  rust_target(_target_name) {
  ^--------------------------
See //content/browser/BUILD.gn:55:1: whence it was called.
rust_static_library("child_process_security_policy_impl") {
^----------------------------------------------------------
See //content/test/BUILD.gn:622:5: which caused the file to be included.
    "//content/browser:for_content_tests",
    ^------------------------------------

../../content/browser/child_process_security_policy_impl.cc:31:10: fatal error: 'content/browser/child_process_security_policy_impl.rs.h' file not found

Issue: NEVA-11096