[appruntime] 151.0.7907.0~1: Add missing |reason| to DidUpdateFaviconURL()
In the upstream CL https://crrev.com/c/7855028 added FaviconUpdateReason
to favicon updates. That changed
WebContentsObserver::DidUpdateFaviconURL() signature by adding |reason|
param.
The overrides of this func in the Neva AppRuntime API is adapted
accordingly.

Without this change, the build fails with errors like the following one:
../../neva/app_runtime/app/app_runtime_page_contents.h:202:67: error: non-virtual member function marked 'override' hides virtual member function
  202 |       const std::vector<blink::mojom::FaviconURLPtr>& candidates) override;
      |                                                                   ^
../../content/public/browser/web_contents_observer.h:774:16: note: hidden overloaded virtual function 'content::WebContentsObserver::DidUpdateFaviconURL' declared here: different number of parameters (3 vs 2)
  774 |   virtual void DidUpdateFaviconURL(
      |                ^

Issue: NEVA-11311