[appruntime] 155.0.8041.0~1: Fix PostCreateThreads() return type
Fixed the build error where `PostCreateThreads()` virtual function had a
different return type (`void`). After the upstream CL
https://crrev.com/c/8290608 it returns `int`.

Without this CL build failed with the error:
../../neva/app_runtime/browser/app_runtime_browser_main_parts.h:77:8:
error: virtual function 'PostCreateThreads' has a different return type
('void') than the function it overrides (which has return type 'int')
   77 |   void PostCreateThreads() override;
      |   ~~~~ ^

AI-assisted (Qwen3.6-35B)

Issue: NEVA-11447