[appruntime] Remove usage of TimeTicks::UnixEpoch()
In the upstream CL https://crrev.com/c/7928095 removed deprecated
base::TimeTicks::UnixEpoch(). Therefore its usage in Neva App-Runtime
API is removed and code adapted to avoid build error:
../../ui/base/ime/linux/neva/input_method_auralinux_neva.cc:107:35:
error: no member named 'UnixEpoch' in 'base::TimeTicks'; did you mean 'base::Time::UnixEpoch'?
  107 |   suppress_non_key_input_until_ = base::TimeTicks::UnixEpoch();

Issue: NEVA-11360