[appruntime] 149.0.7794.0~1: Adapt usage of FromUTF8() in app_runtime_render_frame_observer.cc
In the upstream CL https://cerev.com/c/7760406 which is reland of
https://cerev.com/c/7760402, the FromUTF8() function was renamed to
FromUtf8(). This function has been renamed to match the new name in the
upstream code.
Without this CL the build fails with the error:
../../neva/app_runtime/renderer/app_runtime_render_frame_observer.cc:143:25:
error: no member named 'FromUTF8' in 'blink::WebString'; did you mean 'FromUtf8'?
|   143 |       blink::WebString::FromUTF8(css));
|       |                         ^~~~~~~~
|       |                         FromUtf8
third_party/blink/public/platform/web_string.h:130:20: note: 'FromUtf8' declared here
|   130 |   static WebString FromUtf8(std::string_view s);

Issue: NEVA-11191